travis:
  secure:
    BINSTAR_TOKEN: dTMxGYL/YK1nIrLOB1FmxkrDO8xJDn2roK6OI+XeSOjbytxctNpaEjanHf007Psj+Io2GLi+CpQBdNfqjGOhcg+vGLni9HIZmN4g7I0JuevA5POV3c3/Csol039lkH7gzV/ZPGOx0BozX+4FmR4lu06dAavZ2E0vGJkrIWsVyNA1NSIs27e4r7Ujztw5/dYqhU50B+JkAT57wSXnVQvScujZqi7YZsg8tRR/sOl+AnGaY3jFva5IKKt2hvLxLIv9ZZQtLZOc1tLlg+RMt5LnqnEkVHs/peSwvc2QB/5lXNYiPRnbEZRluhF6Mmo+HNp2C6jVsv3iQ2D6h0u/m00whW+CqAjCYRSTrRn+86zbXYprLIuXvpoA11+EUEoMYcte0+QTJXH1cCy1Ib4niFxrrbK3VkXxfK0qXod+smN+AtQTDAhdZz2S82U+fqGa+36928M550UrgfeKw+7XASiiKO0+2IN1UPoEmezoS5yg2mwiwMSWvoMq21RbDfrgf9d83qx9AvrHXBYMQju23Uy0nPgqCQrNJOfwbw0KeUc5HxSzMSN7afMHzvtFkjfD/b5WFB5dhE1C41W3YsQToQoj+GA/UAoJW/z8Hvp7OWSk50neh3gihdxOqkv0MNokw1bRIZWRBKCG7HWmDG1o67dRug4E3rHOwVUdWzJUwPtjrO0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
